language: csharp

mono:
  - latest

addons:
  apt:
    packages:
    - libunwind8

script: 
  - ./build.sh BuildTestProjects

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
